# CMake generated Testfile for 
# Source directory: /home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1
# Build directory: /home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(buffertest "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/buffertest")
set_tests_properties(buffertest PROPERTIES  WORKING_DIRECTORY "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1" _BACKTRACE_TRIPLES "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;133;add_test;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;137;unittest;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;0;")
add_test(unittest "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/unittest")
set_tests_properties(unittest PROPERTIES  WORKING_DIRECTORY "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1" _BACKTRACE_TRIPLES "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;133;add_test;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;138;unittest;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;0;")
add_test(SchemaTests "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/SchemaTests")
set_tests_properties(SchemaTests PROPERTIES  WORKING_DIRECTORY "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1" _BACKTRACE_TRIPLES "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;133;add_test;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;139;unittest;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;0;")
add_test(LargeSchemaTests "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/LargeSchemaTests")
set_tests_properties(LargeSchemaTests PROPERTIES  WORKING_DIRECTORY "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1" _BACKTRACE_TRIPLES "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;133;add_test;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;140;unittest;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;0;")
add_test(CodecTests "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CodecTests")
set_tests_properties(CodecTests PROPERTIES  WORKING_DIRECTORY "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1" _BACKTRACE_TRIPLES "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;133;add_test;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;141;unittest;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;0;")
add_test(StreamTests "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/StreamTests")
set_tests_properties(StreamTests PROPERTIES  WORKING_DIRECTORY "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1" _BACKTRACE_TRIPLES "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;133;add_test;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;142;unittest;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;0;")
add_test(SpecificTests "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/SpecificTests")
set_tests_properties(SpecificTests PROPERTIES  WORKING_DIRECTORY "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1" _BACKTRACE_TRIPLES "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;133;add_test;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;143;unittest;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;0;")
add_test(DataFileTests "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/DataFileTests")
set_tests_properties(DataFileTests PROPERTIES  WORKING_DIRECTORY "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1" _BACKTRACE_TRIPLES "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;133;add_test;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;144;unittest;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;0;")
add_test(JsonTests "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/JsonTests")
set_tests_properties(JsonTests PROPERTIES  WORKING_DIRECTORY "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1" _BACKTRACE_TRIPLES "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;133;add_test;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;145;unittest;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;0;")
add_test(AvrogencppTests "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/AvrogencppTests")
set_tests_properties(AvrogencppTests PROPERTIES  WORKING_DIRECTORY "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1" _BACKTRACE_TRIPLES "/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;133;add_test;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;146;unittest;/home/andy/bachelor_arbeit/src/confluent-6.2.1/src/avro-cpp-1.8.0-confluent6.2.1/CMakeLists.txt;0;")
